name: test_code
on: [push]
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
     - name: get-repo
       uses: actions/checkout@v3 
  deploy:
    needs: firstjob
    runs-on: ubuntu-latest
    steps:
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
 

