name: test_code
on: [push]
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
     - name: get-repo
       uses: actions/checkout@v3
     - name: install nodejs
       uses: actions/setup-node@v3
 

