name: test_code
on: [push,workflow_dispatch]
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
     - name: get-repo
       uses: actions/checkout@v3 
  deploy:
    needs: firstjob
    runs-on: ubuntu-latest
    steps:
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
  finalizer:
    runs-on: ubuntu-latest
    needs: [deploy,firstjob]
    if: "success()"
    steps:
     - name: finalize repo
       run: "echo hello there"
 

